.github/PULL_REQUEST_TEMPLATE.md
test/e2e/dev/bpdTermsAndConditions.js
test/e2e/dev/faTermsAndConditions.js
test/tests/bpdHbTermsAndConditions.js
test/tests/faHbTermsAndConditions.js

This pr proposes to add test cases and test suite in dev environment to test access to static html files stored ob blob storage

[CEN-1350] Add tests for bpd and fa T&C

---

.pre-commit-config.yaml
README.md
test/common/api/rtdStorage.js
test/common/envs.js
test/e2e/bpdIoCitizenOptInStatus.js
test/performance/rtdCsvTransaction.js
test/performance/rtdGetHashedPans.js
test/performance/rtdGetPublicKey.js
test/performance/rtdGetSalt.js
test/performance/rtdStorage.js
test/performance/rtdStorageUploadInvalidFile.js
test/smoke/bpdIoPaymentInstrument.js
test/smoke/bpdTermsAndConditions.js
test/smoke/faTermsAndConditions.js
test/smoke/rtdCsvTransaction.js
test/smoke/rtdStorage.js

This PR adds performance tests for all endpoint involved in the upcoming release.
It also integrates pre-commit hooks to enable auto-linting via prettier before pushing to remote.
- add performance tests for RTD endpoints
- pre-commit configuration
it enables extensive testing of the RTD APIs.

[CEN-1455] Expanded load suite / pre-commit with prettier integration

---

test/common/api/cdcSogeiHealthCheck.js
test/performance/cdcSogei.js

In order to test availability and throughput of "Carta della Cultura" / SOGEI APIs, this PR proposes to test their health-check endpoint 
- New test case for health-check endpoint `/CDCUtenteWS/rest/unsecured/versione`
- New performance test 
In order to manage the traffic burst we expect when users will request _Carta della Cultura_, APIs performance must be assessed

[CDC-52] Test SOGEI HealthCheck

---

test/common/utils.js
test/performance/faHbPaymentInstruments.js

This PR adds the random fiscal code in FA HB Payment Instrument API load test. While adding this feature, it was noticed a bug in the function that generates the random fiscal codes (part of the "utils"), it has been fixed.
- Add random fiscal in request body of FA HB Payment Instruments API load test.
- Fix of a in issue in the function that creates random fiscal code.
This modification was to improve the load test and make it more realistic.
A single test has been modified.

[CEN-1580] Add random fiscal code in FA HB Payment Instruments API load test

---

test/common/api/cdcSogeiHealthCheck.js
test/performance/cdcSogei.js

This PR proposes to fix CDC health check test by setting the product to be used on APIM 
- Modify the header containing the APIM subscription key by setting the product to be used on APIM
- Modify the load of the performance test
- Fix the path
This PR solves the problem of processing the product policy on APIM which contains the token transcode logic

[CDC-58] Fix health check test

---

test/common/api/bpdIoLogin.js
test/e2e/cdcSogeiTranscodeToken.js

This PR proposes to refactor SOGEI API test to use IO product on CSTAR APIM.
- New routine with a fully configurable path to get a test IO Session Token
- Refactor af existing test to use IO Product on Cstar APIM
This PR is required to generate test wether the JWS token generated by CSTAR APIM can be verified by a third party.
]

[CDC-58] Refactor SOGEI Api Test to test IO Token transcode

---

test/common/api/idpayOnbardingCitizen.js
test/e2e/cdcRequestWithIOToken.js
test/e2e/idpayOnboarding.js

Test Accept T&C
- New case to test acceptance of T&C
- New Test Suite
This test allows to test the use case of T&C acceptance. Moreover it's the first test to check behaviour of IDPAY/CITIZEN end-to-end

[ISB 10] Add test IDPAY put T&C

---

test/common/api/rtdPaymentInstrumentManager.js
test/smoke/rtdPaymentInstrumentManager.js

This PR introduce smoke test for v2 api of rtd-payment-instrument apis

[RTD-301] Added smoke test payment instrument v2

---

test/performance/taeDownloadSenderAdeAckFile.js

This PR proposes to fix a typo in the import path of the downloadAdeAck file.
- Fix filename in import path
The path is actually pointing to a file that does not exist.

[RTD-355] Fix file import ade ack

---

test/e2e/taeFakeAbiToFiscalCodeMap.js

This PR proposes to add TPAY1 mapping in abi to fiscal code test.

[RTD-647] Add TPAY1 translation in ABI to fiscal code mapping test

---

test/common/api/pmWalletExt.js
test/e2e/pmTestIdWallet.js

Test access to PM via PagoPA Platform APIM
- New test case
- New test suite
Access PM via Platform APIM

[ISB-487] Add PM Wallet test

---

test/broder/postman/payment_instrument_apis.postman_collection.json
test/smoke/rtdPaymentInstrumentManager.js

This PR adds test case to download hashpan-par file generated by ADF pipeline.
- K6 test suite
- Postman collection tests

[RTD-805] Add hashpan v3 tests

---

env.local.sample
test/e2e/faAddMerchant.js

This PR adds an e2e test that allows the addition of a merchant to be tested in all environments (including PROD).
- add e2e test to add a merchant
This is used to test the proper onboarding of a merchant.

[CSFA-63] add e2e test to add a merchant

---

test/e2e/rtdMauthFilter.js

This PR is aimed at testing if client with mauth can access api using IO endpoints

[RTD-1030] Test mauth

---

.gitignore
CODEOWNERS
test/e2e/taeFakeAbiToFiscalCodeMap.js
test/smoke/rtdCsvTransaction.js

This PR proposes to add EURON mapping in abi to fiscal code test.

[RTD-1334] Add EURON translation in ABI to fiscal code mapping test

---

test/e2e/taeFakeAbiToFiscalCodeMap.js

This PR proposes to add UBER1 mapping in abi to fiscal code test.

[RTD-1335] Add UBER1 translation in ABI to fiscal code mapping test

---

test/common/assertions.js
test/e2e/rtdMauthFilter.js
test/smoke/rtdBatchServiceDeprecation.js
test/smoke/rtdCsvTransaction.js
test/smoke/taeApi.js

This PR proposes to add the smoke tests for the batch service deprecation.

[RTD-1407] Add tests for batch service deprecation

---

test/smoke/rtdBatchServiceDeprecation.js

This PR proposes to update the smoke test on batch service deprecation

[RTD-1614] update smoke test deprecation batch service

---

pipelines/deploy-pipelines.yml
requirements.txt
test/performance/idpayOnboardingAPI.js

Isolate API getInitiative from onboarding script

feat: IDP-1280 riallineare test di performance

---

pipelines/deploy-pipelines.yml
test/common/api/idPayPaymentDiscount.js
test/common/stageUtils.js
test/performance/idPayPaymentDiscountAPI.js
test/performance/idpayOnboardingAPI.js

Add performance test of discount payment
Script idPayPaymentDiscountAPI.js

feat: IDP-1034-test-di-performance-app-io-costante-di-un-pagamento-a-sconto

---

pipelines/deploy-pipelines.yml

added refund export after payments

feat: Idp 1328 stage performance rimborsi

---

pipelines/deploy-pipelines.yml
test/common/dynamicScenarios/utils.js
test/common/utils.js
test/performance/idpay/idPayPaymentDiscountAPI.js

Using multiple merchant read by file manually uploaded into AzureDevops as SecureFile

feat:IDP-1035 merchant from list

---

test/common/dynamicScenarios/scenarios/constantArrivalRate.js
test/common/dynamicScenarios/scenarios/rampingArrivalRate.js
test/common/dynamicScenarios/scenarios/rampingGrowingArrivalRate.js

relaxing VU allocation when configuring rate based scenario

feat: relaxing available VU

---

README.md
test/common/dynamicScenarios/defaultOptions.js
test/common/dynamicScenarios/envVars.js
test/common/dynamicScenarios/thresholds/thresholdsBuilder.js
test/performance/idpay/idPayPaymentDiscountAPI.js
test/performance/idpay/idpayOnboardingAPI.js
test/performance/idpay/ioPutEnrollInstrumentIssuer.js

Tagging also HttpReqFailed by apiName
Accepting threshold override by apiName

Handling http req failed by api

---

test/common/dynamicScenarios/envVars.js

fix: fixed name env vars for SCRIPT_ENV

---

pipelines/deploy-pipelines.yml
test/common/dynamicScenarios/utils.js
test/common/utils.js

fixed CsvSeparator not recognized when too few records

fix: Idp 1520 fix cf index reading

---

requirements.txt

This PR adds aiohttp and asyncio as dependencies for cstar-cli

chore: [IDP-1596] update cli requirements.txt

---

README.md
pipelines/deploy-pipelines.yml
test/common/api/idpay/idpayOnboardingCitizen.js
test/common/api/idpay/idpayWallet.js
test/common/dynamicScenarios/envVars.js
test/common/idpay/envVars.js
test/common/utils.js
test/performance/idpay/getWalletDetails.js
test/performance/idpay/idPayPaymentDiscountAPI.js
test/performance/idpay/idpayOnboardingAPI.js
test/performance/idpay/ioPutEnrollIban.js
test/performance/idpay/putTokenPdv.js

onboarding performance test executable bypassing APIm

feat: IDP-1571 onboard throug ingress

---

pipelines/deploy-pipelines.yml

Integrating userId list generation

feat: IDP-1594 cstar cli user id gen integration

---

test/common/api/idpay/idPayPaymentDiscount.js
test/common/dynamicScenarios/envVars.js
test/common/idpay/envVars.js
test/common/utils.js
test/performance/idpay/idPayPaymentDiscountAPI.js

payment performance test through ingress

feat: IDP-1572 payment through ingress

---

pipelines/deploy-pipelines.yml
test/common/api/idpay/idpayOnboardingCitizen.js
test/performance/idpay/idpayCheckInitiativeBudgetAPI.js
test/performance/idpay/idpayOnboardingAPI.js

feat:IDP-1409 checkInitiativeBudget performance test

---

pipelines/deploy-pipelines.yml
test/common/api/idpay/idpayInitiative.js
test/performance/idpay/idpayInitiativeAPI.js

- Added Delete Initiative script.
This script is going to use the delete initiative API for performance tests

feat: Idp 1600 add stage delete su pipeline di performance

---

pipelines/deploy-pipelines.yml

Fixed k6 result dir configuration, broken after xk6 migration

fix: fix result dir config

---

pipelines/deploy-pipelines.yml

This PR proposes to change the self hosted agent. The new one has more resources and it's a better fit to run performance tests

[IDP-1911] change self hosted agent for performance scope

---

test/performance/idpay/idpayOnboardingAPI.js

This PR proposes to remove the 1 second sleep at the end of onboarding script

[IDP-1730] remove sleep in onboarding script

---

test/performance/idpay/idpayOnboardingAPI.js

fix: [RTD-2004] remove get wallet from onboarding tests

---

test/common/api/idpay/idPayPaymentDiscount.js

fix: fix create-trx URL

---

pipelines/deploy-pipelines.yml

fix: Fix merchant upload api

---

pipelines/deploy-pipelines.yml

fixed evaluation logic executed to check if the Refund Export should be force at the end of the test

fix: fix force export activation condition
